### ISSUE TITLE
error after npm start

### ISSUE THREAD

**Issue by swapnilhworld** [DHARESHWAR/spring-websocket#17]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:424:7)
    at noopServiceWorkerMiddleware (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\Swapnil\Dev\Learn\Reactjs\websocket-reactjs-master\node_modules\express\lib\router\layer.js:95:5)

**Comment by lmoroni-mt** [comment]
Update react-scripts version at 3.4.0
